remove-cost: 1000
date-format: "yyyy-MM-dd HH:mm:ss"

claimable-items:
  - DIAMOND_SWORD
  - NETHERITE_SWORD
  - GOLDEN_SWORD
  - IRON_SWORD
  - STONE_SWORD
  - WOODEN_SWORD
  # Pickaxes
  - DIAMOND_PICKAXE
  - NETHERITE_PICKAXE
  - GOLDEN_PICKAXE
  - IRON_PICKAXE
  - STONE_PICKAXE
  - WOODEN_PICKAXE
  # Helmets
  - DIAMOND_HELMET
  - NETHERITE_HELMET
  - GOLDEN_HELMET
  - IRON_HELMET
  - CHAINMAIL_HELMET
  - LEATHER_HELMET
  - TURTLE_HELMET
  # Chestplates
  - DIAMOND_CHESTPLATE
  - NETHERITE_CHESTPLATE
  - GOLDEN_CHESTPLATE
  - IRON_CHESTPLATE
  - CHAINMAIL_CHESTPLATE
  - LEATHER_CHESTPLATE
  # Leggings
  - DIAMOND_LEGGINGS
  - NETHERITE_LEGGINGS
  - GOLDEN_LEGGINGS
  - IRON_LEGGINGS
  - CHAINMAIL_LEGGINGS
  - LEATHER_LEGGINGS
  # Boots
  - DIAMOND_BOOTS
  - NETHERITE_BOOTS
  - GOLDEN_BOOTS
  - IRON_BOOTS
  - CHAINMAIL_BOOTS
  - LEATHER_BOOTS
  # Special
  - ELYTRA
